### PR TITLE
Update RTS for DSpace 7

### PR DESCRIPTION
**Pull request by KingKrimmson**
This PR brings RTS up-to-date and functional in DSpace 7. This PR does _not_ include additional functionality for storing/restoring entity relationships, _nor_ does it implement tests of such functionality.

The following dependencies should be updated by DuraCloud, if possible, to bring them in-line with DSpace 7:
```
org.duracloud:common-queue --> com.amazonaws:aws-java-sdk-sqs:1.11.490
org.duracloud:common-json --> org.codehaus.jackson:jackson-xc:1.9.13
org.duracloud:common --> org.apache.httpcomponents:httpmime:4.5.3
org.duracloud.db:account-management-db-model --> org.springframework.security:spring-security-core:5.2.2.RELEASE
```

At this time, these dependencies (or their children) must be excluded from `dspace-replicate` for mvn to correctly build:
```
<dependency>
         <groupId>org.dspace</groupId>
         <artifactId>dspace-replicate</artifactId>
         <version>7.0-SNAPSHOT</version>
         <exclusions>
            <exclusion>
               <groupId>com.amazonaws</groupId>
               <artifactId>jmespath-java</artifactId>
            </exclusion>
            <exclusion>
               <groupId>com.amazonaws</groupId>
               <artifactId>aws-java-sdk-core</artifactId>
            </exclusion>
            <exclusion>
               <groupId>org.codehaus.jackson</groupId>
               <artifactId>jackson-mapper-asl</artifactId>
            </exclusion>
            <exclusion>
               <groupId>org.codehaus.jackson</groupId>
               <artifactId>jackson-core-asl</artifactId>
            </exclusion>
            <exclusion>
               <groupId>org.apache.httpcomponents</groupId>
               <artifactId>httpmime</artifactId>
            </exclusion>
            <exclusion>
               <groupId>org.springframework.security</groupId>
               <artifactId>spring-security-core</artifactId>
            </exclusion>
         </exclusions>
      </dependency>
```

### CODE REVIEW

**Comment by cwilper** [comment]
Just an observation. I see the tests are failing with:

```
java.lang.RuntimeException: DSpace home directory could not be determined. It MUST include a subpath of '/config/config-definition.xml'. Please consider setting the 'dspace.dir' system property or ensure the dspace-api.jar is being run from [dspace]/lib/.
```

Usually when I've seen this type of error, it means DSpace is trying to start the kernel, but the test environment has not been built yet. In DSpace 6 and 7, when running ITs, typically a test environment automatically gets built, and when tests are launched, the right -D properties as passed in the point to e.g. the dspace.dir.

**Comment by mikejritter** [comment]
@cwilper I wanted to add a few notes here for future reference to add some context for the testing currently in the RTS.

* I also struggled with getting the kernel to load properly when adding tests (variations of the `RuntimeException` you posted and other exceptions related to init), and initially went down a similar route April did by trying to use the test classes from DSpace to handle initialization.
    * As you noted the ITs for DSpace create a test environment that DSpace can use to initialize the kernel. I was able to copy over the test environment but wasn't sure of any way to do create it so I did not end up pursuing it as much as I would have liked.
* I then opted to create a harness which would handle as much of the kernel init as was needed and tried to trick the kernel into thinking it had a fully functional environment
    * While not perfect this allowed me to get to a point that I could test the code written for the BagIt packagers
    * I'll note that it's hard to be completely satisfied with this approach as there ended up being a large usage of mocks both for the initialization of the kernel and usage of the kernel in the RTS (retrieving static factories, DSpaceObjectService interactions, etc).
    * There's also a very frustrating limitation here that certain static methods break the testing, e.g. `PackageUtils.translateGroupNameForExport`
* Looking at DSpace 7, it seems that we cannot trick the kernel as easily into thinking everything has been initialized. This is especially true for interactions with the database where I found I was not able to quickly plug in H2 and get the kernel created. I don't recall exactly what issue I ran into but could take a look again if you're interested. 

Overall I'm not sure how much it's worth looking into the current approach to testing for DSpace 7 given that it feels like the init changes are incompatible. This leads us to need a way to create the test environment for the RTS, though unfortunately I feel limited in my experience with maven plugins to know what is and isn't possible.

**Comment by cwilper** [comment]
@mikejritter thanks for your writeup.

I took a fresh look at this after being away from it for a few months. I agree that we should look toward a new way of creating the test environment for RTS. As part of that, I wonder if establishing a hard separation between pure unit tests and integration tests (with a running DSpace) would be good here. 

On the surface, it seems the intent of the existing tests is to exercise dspace-replicate functionality in isolation. It seems like an unintended consequence that the DSpace kernel tries to come along for the ride. I wonder if the test coverage that is achieved currently could be reasonably approximated by creating more pure mocks of the various DSpace services so we can avoid the need altogether for a DSpace kernel to be present. At least in the short term.

**Comment by KingKrimmson** [comment]
This has now been replaced by https://github.com/DSpace/dspace-replicate/pull/60

**Pull request closed without merging**
